In [76]:
import pandas as pd 
import numpy as np

In [77]:
data = pd.read_csv("Datasets\cars.csv")
print(data)

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [78]:
X = data.iloc[:,0:4:]
print(X)

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [79]:
y = data.iloc[:,-1]
print(y)

0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8123    320000
8124    135000
8125    382000
8126    290000
8127    290000
Name: selling_price, Length: 8128, dtype: int64

In [80]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [81]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [82]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [83]:
X_train_encoded = ohe.fit_transform(X_train[['fuel','owner']])

In [84]:
X_test_encoded = ohe.transform(X_test[['fuel','owner']])

In [85]:
X_test_encoded.shape

(1626, 7)

In [86]:
np.hstack((X_train[['brand','km_driven']].values,X_train_encoded))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

In [87]:
counts = data['brand'].value_counts()
print(counts)

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [88]:
data['brand'].nunique()
thar = 100

In [89]:
repl = counts[counts <= thar].index

In [98]:
pd.get_dummies(data['brand'].replace(repl, 'uncommon')).astype(int).sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2788,0,0,0,0,1,0,0,0,0,0,0,0,0
2838,0,0,0,0,0,0,0,0,0,0,1,0,0
1199,0,0,0,0,0,0,1,0,0,0,0,0,0
6808,0,0,0,0,1,0,0,0,0,0,0,0,0
1407,0,0,0,0,0,0,0,0,0,0,0,0,1
729,0,0,0,0,0,0,0,0,0,1,0,0,0
6049,0,0,0,0,0,0,1,0,0,0,0,0,0
251,0,0,0,0,1,0,0,0,0,0,0,0,0
4589,0,0,0,0,0,0,0,0,0,0,1,0,0
5705,0,0,0,0,0,1,0,0,0,0,0,0,0